# Generated by Django 5.2.16 on 2026-08-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email')], max_length=10, verbose_name='Способ регистрации'),
        ),
    ]
