# Generated by Django 5.2.16 on 2026-08-05 10:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(db_index=True, help_text='Код автоматически сохраняется в верхнем регистре без пробелов по краям.', max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало периода активации')),
                ('valid_until', models.DateTimeField(blank=True, help_text='После этой даты код нельзя активировать. Оставьте пустым для отсутствия общей даты окончания.', null=True, verbose_name='Окончание периода активации')),
                ('duration_days', models.PositiveIntegerField(blank=True, default=30, help_text='Оставьте пустым, если бонус после активации должен действовать бессрочно.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок бонуса после активации, дней')),
                ('max_global_activations', models.PositiveIntegerField(blank=True, help_text='Общий лимит для всех пользователей. Оставьте пустым для отсутствия ограничения.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум активаций кода')),
                ('max_user_activations', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум активаций одним пользователем')),
                ('activation_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество успешных активаций')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Чит-код',
                'verbose_name_plural': 'Чит-коды',
                'ordering': ['name', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='cheat_valid_until_after_from'), models.CheckConstraint(condition=models.Q(('max_global_activations__isnull', True), ('max_global_activations__gte', 1), _connector='OR'), name='cheat_global_limit_positive'), models.CheckConstraint(condition=models.Q(('max_user_activations__gte', 1)), name='cheat_user_limit_positive'), models.CheckConstraint(condition=models.Q(('duration_days__isnull', True), ('duration_days__gte', 1), _connector='OR'), name='cheat_duration_positive')],
            },
        ),
        migrations.CreateModel(
            name='CheatReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('streak_to_star', 'Количество правильных ответов до звезды'), ('bonus_star', 'Выдать звёзды'), ('double_stars', 'Множитель звёзд'), ('bonus_points', 'Дополнительные очки'), ('xp_multiplier', 'Множитель опыта'), ('unlock_mode', 'Открыть игровой режим'), ('freeze_streak', 'Не сбрасывать серию'), ('show_correct_answer', 'Показывать правильный ответ'), ('unlimited_hints', 'Безлимитные подсказки'), ('unlimited_lives', 'Бесконечные жизни'), ('unlock_avatar', 'Разблокировать аватар'), ('unlock_theme', 'Разблокировать тему'), ('unlock_background', 'Разблокировать фон'), ('enable_event', 'Включить событие')], max_length=50, verbose_name='Тип награды')),
                ('reward_data', models.JSONField(default=dict, help_text='Например: {"answers": 8}, {"multiplier": 2} или {"stars": 5}.', verbose_name='Параметры награды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('cheat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='cheats.cheatcode', verbose_name='Чит-код')),
            ],
            options={
                'verbose_name': 'Награда чит-кода',
                'verbose_name_plural': 'Награды чит-кодов',
                'ordering': ['cheat', 'reward_type'],
                'constraints': [models.UniqueConstraint(fields=('cheat', 'reward_type'), name='cheat_unique_reward_type')],
            },
        ),
        migrations.CreateModel(
            name='UserCheat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата активации')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания бонуса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('activation_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при активации')),
                ('activation_user_agent', models.TextField(blank=True, verbose_name='User-Agent при активации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('cheat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_activations', to='cheats.cheatcode', verbose_name='Чит-код')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_activations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активация чит-кода',
                'verbose_name_plural': 'Активации чит-кодов',
                'ordering': ['-activated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='cheat_user_active_idx'), models.Index(fields=['cheat', 'activated_at'], name='cheat_code_activated_idx'), models.Index(fields=['expires_at'], name='cheat_expiration_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('activated_at')), _connector='OR'), name='cheat_expiry_after_activation')],
            },
        ),
    ]
