"""Initial database

Revision ID: 494348739730
Revises: 
Create Date: 2026-07-03 12:45:31.341139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494348739730'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
