# Generated by Django 5.2.16 on 2026-08-03 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#87CEEB', max_length=7, verbose_name='Цвет фона')),
                ('background_image', models.CharField(blank=True, default='', max_length=255, verbose_name='Фоновое изображение')),
                ('background_music', models.BooleanField(default=True, verbose_name='Музыка')),
                ('success_sound', models.BooleanField(default=True, verbose_name='Звук успеха')),
                ('fail_sound', models.BooleanField(default=True, verbose_name='Звук ошибки')),
                ('background_volume', models.PositiveSmallIntegerField(default=50)),
                ('success_volume', models.PositiveSmallIntegerField(default=50)),
                ('fail_volume', models.PositiveSmallIntegerField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
