# Generated by Django 5.2.16 on 2026-08-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
    ]
