# Generated by Django 5.2.16 on 2026-08-03 14:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_create_missing_user_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='background_music',
            field=models.BooleanField(default=True, verbose_name='Фоновая музыка'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='background_volume',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Громкость фоновой музыки'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='fail_sound',
            field=models.BooleanField(default=True, verbose_name='Звук неправильного ответа'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='fail_volume',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Громкость ошибки'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='success_sound',
            field=models.BooleanField(default=True, verbose_name='Звук правильного ответа'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='success_volume',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Громкость правильного ответа'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
