# Generated by Django 5.2.16 on 2026-08-04 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Ключ Django-сессии')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Код страны')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city_name', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('browser_name', models.CharField(blank=True, max_length=100, verbose_name='Браузер')),
                ('browser_version', models.CharField(blank=True, max_length=50, verbose_name='Версия браузера')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Операционная система')),
                ('device_type', models.CharField(choices=[('desktop', 'Стационарный компьютер'), ('tablet', 'Планшет'), ('mobile', 'Смартфон'), ('bot', 'Робот'), ('unknown', 'Не определено')], default='unknown', max_length=20, verbose_name='Тип устройства')),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина экрана')),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота экрана')),
                ('viewport_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина окна браузера')),
                ('viewport_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота окна браузера')),
                ('pixel_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Плотность пикселей')),
                ('browser_language', models.CharField(blank=True, max_length=30, verbose_name='Язык браузера')),
                ('timezone_name', models.CharField(blank=True, max_length=100, verbose_name='Часовой пояс браузера')),
                ('touch_points', models.PositiveSmallIntegerField(default=0, verbose_name='Количество точек касания')),
                ('cpu_cores', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Логических процессоров')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Первое действие')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последнее действие')),
                ('request_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество запросов')),
                ('last_path', models.CharField(blank=True, max_length=500, verbose_name='Последняя страница')),
                ('client_context_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Получены данные браузера')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия посещения',
                'verbose_name_plural': 'Сессии посещений',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('browser_name', models.CharField(blank=True, max_length=100, verbose_name='Браузер')),
                ('browser_version', models.CharField(blank=True, max_length=50, verbose_name='Версия браузера')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Операционная система')),
                ('device_type', models.CharField(choices=[('desktop', 'Стационарный компьютер'), ('tablet', 'Планшет'), ('mobile', 'Смартфон'), ('bot', 'Робот'), ('unknown', 'Не определено')], default='unknown', max_length=20, verbose_name='Тип устройства')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Код страны')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city_name', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('logged_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('visit_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to='analytics.visitsession', verbose_name='Сессия посещения')),
            ],
            options={
                'verbose_name': 'Успешный вход',
                'verbose_name_plural': 'Успешные входы',
                'ordering': ['-logged_in_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['user', 'last_seen_at'], name='analytics_user_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['ip_address', 'last_seen_at'], name='analytics_ip_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['country_code', 'last_seen_at'], name='analytics_country_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['user', 'logged_in_at'], name='analytics_login_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['ip_address', 'logged_in_at'], name='analytics_login_ip_time_idx'),
        ),
    ]
