# Generated by Django 5.2.16 on 2026-08-04 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('add', 'Сложение'), ('sub', 'Вычитание'), ('mul', 'Умножение'), ('div', 'Деление'), ('all', 'Все действия'), ('review', 'Повтор ошибок')], max_length=10, verbose_name='Режим')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('abandoned', 'Прервана')], default='active', max_length=12, verbose_name='Статус')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='Неправильных ответов')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='Лучшая серия сессии')),
                ('stars_earned', models.PositiveIntegerField(default=0, verbose_name='Заработано звёзд')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер примера в сессии')),
                ('operation', models.CharField(choices=[('add', 'Сложение'), ('sub', 'Вычитание'), ('mul', 'Умножение'), ('div', 'Деление')], max_length=3, verbose_name='Действие')),
                ('num1', models.IntegerField(verbose_name='Первое число')),
                ('num2', models.IntegerField(verbose_name='Второе число')),
                ('correct_answer', models.IntegerField(verbose_name='Правильный ответ')),
                ('user_answer', models.IntegerField(blank=True, null=True, verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Ответ правильный')),
                ('shown_at', models.DateTimeField(auto_now_add=True, verbose_name='Время показа')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время ответа, мс')),
                ('is_review', models.BooleanField(default=False, verbose_name='Повтор ошибки')),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_attempts', to='game.gamequestion', verbose_name='Исходный ошибочный пример')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.gamesession', verbose_name='Игровая сессия')),
            ],
            options={
                'verbose_name': 'Игровой пример',
                'verbose_name_plural': 'Игровые примеры',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='StarTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(verbose_name='Количество звёзд')),
                ('reason', models.CharField(choices=[('streak', 'Серия правильных ответов'), ('achievement', 'Достижение'), ('bonus_code', 'Бонус-код'), ('event', 'Событие'), ('admin', 'Изменение администратором'), ('correction', 'Корректировка')], max_length=20, verbose_name='Причина')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='star_transactions', to='game.gamesession', verbose_name='Игровая сессия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция со звёздами',
                'verbose_name_plural': 'Операции со звёздами',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='Всего звёзд')),
                ('total_correct', models.PositiveBigIntegerField(default=0, verbose_name='Всего правильных ответов')),
                ('total_wrong', models.PositiveBigIntegerField(default=0, verbose_name='Всего неправильных ответов')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='Лучшая серия')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='Количество игровых сессий')),
                ('total_answer_time_ms', models.PositiveBigIntegerField(default=0, verbose_name='Общее время ответов, мс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_statistics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игровая статистика пользователя',
                'verbose_name_plural': 'Игровая статистика пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'status'], name='game_session_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'started_at'], name='game_session_user_started_idx'),
        ),
        migrations.AddIndex(
            model_name='gamequestion',
            index=models.Index(fields=['session', 'answered_at'], name='game_q_sess_answer_idx'),
        ),
        migrations.AddIndex(
            model_name='gamequestion',
            index=models.Index(fields=['session', 'is_correct'], name='game_q_sess_result_idx'),
        ),
        migrations.AddIndex(
            model_name='gamequestion',
            index=models.Index(fields=['operation', 'is_correct'], name='game_q_oper_result_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamequestion',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_number'), name='game_unique_question_number'),
        ),
        migrations.AddConstraint(
            model_name='gamequestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answered_at__isnull', True), ('is_correct__isnull', True), ('user_answer__isnull', True)), models.Q(('answered_at__isnull', False), ('is_correct__isnull', False), ('user_answer__isnull', False)), _connector='OR'), name='game_question_answer_state_valid'),
        ),
        migrations.AddIndex(
            model_name='startransaction',
            index=models.Index(fields=['user', 'created_at'], name='game_star_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='startransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='game_star_transaction_nonzero'),
        ),
    ]
