# Generated by Django 5.2.16 on 2026-08-06 07:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_create_missing_user_statistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avoid_recent_duplicates', models.BooleanField(default=True, verbose_name='Не повторять недавние примеры')),
                ('recent_questions_limit', models.PositiveSmallIntegerField(default=100, help_text='Сколько последних примеров учитывать при проверке повторений.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Размер журнала повторов')),
                ('auto_increase_difficulty', models.BooleanField(default=False, verbose_name='Автоматически повышать сложность')),
                ('correct_answers_per_level', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Правильных ответов до повышения уровня')),
                ('maximum_difficulty_level', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальный уровень сложности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Общие настройки генератора',
                'verbose_name_plural': 'Общие настройки генераторов',
            },
        ),
        migrations.CreateModel(
            name='OperationGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', 'Сложение'), ('sub', 'Вычитание'), ('mul', 'Умножение'), ('div', 'Деление')], max_length=3, verbose_name='Математическое действие')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Использовать действие')),
                ('mixed_mode_weight', models.PositiveSmallIntegerField(default=25, help_text='Чем больше значение, тем чаще действие появляется в режиме «Все действия».', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес в смешанном режиме')),
                ('first_operand_min', models.IntegerField(default=1, verbose_name='Минимальное первое число')),
                ('first_operand_max', models.IntegerField(default=100, verbose_name='Максимальное первое число')),
                ('second_operand_min', models.IntegerField(default=1, verbose_name='Минимальное второе число')),
                ('second_operand_max', models.IntegerField(default=100, verbose_name='Максимальное второе число')),
                ('operands_count', models.PositiveSmallIntegerField(default=2, help_text='Для первой версии поддерживаются значения от 2 до 4.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Количество операндов')),
                ('minimum_answer', models.IntegerField(blank=True, null=True, verbose_name='Минимальный результат')),
                ('maximum_answer', models.IntegerField(blank=True, null=True, verbose_name='Максимальный результат')),
                ('allow_negative_result', models.BooleanField(default=False, help_text='Применяется только к вычитанию.', verbose_name='Разрешать отрицательный результат')),
                ('allow_remainder', models.BooleanField(default=False, help_text='Зарезервировано для будущего режима с десятичными ответами.', verbose_name='Разрешать деление с остатком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('generation_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='game.usergenerationsettings', verbose_name='Общие настройки')),
            ],
            options={
                'verbose_name': 'Настройки математического действия',
                'verbose_name_plural': 'Настройки математических действий',
                'ordering': ['generation_settings', 'operation'],
                'indexes': [models.Index(fields=['generation_settings', 'operation'], name='game_generation_operation_idx')],
                'constraints': [models.UniqueConstraint(fields=('generation_settings', 'operation'), name='game_unique_generation_operation'), models.CheckConstraint(condition=models.Q(('first_operand_max__gte', models.F('first_operand_min'))), name='game_first_operand_range_valid'), models.CheckConstraint(condition=models.Q(('second_operand_max__gte', models.F('second_operand_min'))), name='game_second_operand_range_valid'), models.CheckConstraint(condition=models.Q(('minimum_answer__isnull', True), ('maximum_answer__isnull', True), ('maximum_answer__gte', models.F('minimum_answer')), _connector='OR'), name='game_answer_range_valid'), models.CheckConstraint(condition=models.Q(('operands_count__gte', 2), ('operands_count__lte', 4)), name='game_operands_count_valid')],
            },
        ),
    ]
