# Generated by Django 5.2.16 on 2026-08-06 10:00

from django.db import migrations, models


def populate_question_operands(
    apps,
    schema_editor,
):
    GameQuestion = apps.get_model(
        "game",
        "GameQuestion",
    )

    questions = (
        GameQuestion.objects
        .filter(operands=[])
        .only(
            "pk",
            "num1",
            "num2",
            "operands",
        )
    )

    batch = []

    for question in questions.iterator(
        chunk_size=1000
    ):
        question.operands = [
            question.num1,
            question.num2,
        ]

        batch.append(question)

        if len(batch) >= 1000:
            GameQuestion.objects.bulk_update(
                batch,
                [
                    "operands",
                ],
                batch_size=1000,
            )

            batch.clear()

    if batch:
        GameQuestion.objects.bulk_update(
            batch,
            [
                "operands",
            ],
            batch_size=1000,
        )


def clear_question_operands(
    apps,
    schema_editor,
):
    GameQuestion = apps.get_model(
        "game",
        "GameQuestion",
    )

    GameQuestion.objects.update(
        operands=[],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_create_generation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='operands',
            field=models.JSONField(blank=True, default=list, help_text='Упорядоченный список чисел примера. Например: [5, 7, 9].', verbose_name='Операнды'),
        ),
        migrations.RunPython(
            populate_question_operands,
            clear_question_operands,
        ),
    ]
