# Generated by Django 5.2.16 on 2026-08-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamequestion_operands'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergenerationsettings',
            name='difficulty_profile',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('custom', 'Свой')], default='medium', max_length=20, verbose_name='Профиль сложности'),
        ),
    ]
